language: php

php:
  - 7.0

branches:
  - master

install:
  - cd ..
  - mkdir PocketMine-MP && cd PocketMine-MP
  - mkdir plugins
  - wget -O plugins/PluginChecker.php https://gist.githubusercontent.com/KnownUnown/982bbbef98e86ddfc5b5aac570195024/raw/ac2001b78600a51d31acce3bb440732c4c0c1be3/PluginChecker.php
  - wget -O plugins/DevTools.phar https://github.com/pmmp/PocketMine-DevTools/releases/download/v1.12.1/DevTools_v1.12.1.phar
  - wget -O PocketMine-MP.phar https://poggit.pmmp.io/r/10479/PocketMine-MP.phar
  - pecl install channel://pecl.php.net/pthreads-3.1.6
  - pecl install channel://pecl.php.net/weakref-0.3.2
  - echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7

before_script:
  - php -dphar.readonly=0 plugins/DevTools.phar --make $TRAVIS_BUILD_DIR --out plugins/SheepPlugin-$TRAVIS_COMMIT.phar

script:
  - php PocketMine-MP.phar --no-wizard --disable-readline --debug.level=2 --pluginchecker.target=SheepPlugin | tee output.txt
  - grep "Success" output.txt
