language: php

php:
  - 7.0

branches:
  - master

install:
  - cd ..
  - mkdir PocketMine-MP && cd PocketMine-MP
  - mkdir plugins
  - wget -O plugins/PluginChecker.php http://gist.githubusercontent.com/Zachari/41676cd796034d11b6e34a9cf46c3bf7/raw/2503f4cf77bb34dcb158b1f1245da6658a410486/PluginChecker.php
  - wget -O plugins/DevTools.phar http://github.com/pmmp/PocketMine-DevTools/releases/download/v1.12.1/DevTools_v1.12.1.phar
  - wget -O PocketMine-MP.phar http://poggit.pmmp.io/r/10480/PocketMine-MP.phar
  - pecl install channel://pecl.php.net/pthreads-3.1.6
  - pecl install channel://pecl.php.net/weakref-0.3.2
  - echo | pecl install channel://pecl.php.net/yaml-2.0.0RC7

before_script:
  - php -dphar.readonly=0 plugins/DevTools.phar --make $TRAVIS_BUILD_DIR --out plugins/SheepPlugin-$TRAVIS_COMMIT.phar

script:
  - php PocketMine-MP.phar --no-wizard --disable-readline --debug.level=2 --pluginchecker.target=SheepPlugin | tee output.txt
  - grep "Success" output.txt
